### ISSUE TITLE
add link to github pull request/issue page for empty information

### ISSUE THREAD

**Issue by kmindi** [cryptocatalog/ultimate-crypto-comparison#14]
For example, if there is a attribute (heading) that has no value right now, there should be a link/button to contribute this information easily.

**Comment by kmindi** [comment]
how is this fixed by 6f92031

**Comment by schneisn** [comment]
This was an error. I pulled the rewrite from the base repository and their commits reference some issues. These references actually belong to the repository of the base-framework but GitHub thinks they reference the issues in this repository.  
I had to pull the rewrite branch from the base repository because we need to get future updates of them and this is easier with the same history.

**Comment by schneisn** [comment]
Added in 1696ab9b919f588c1b8192d231fec6fab71b3169
