### ISSUE TITLE
Use git scrabber to automatically add libraries

### ISSUE THREAD

**Issue by MOSjens** [cryptocatalog/ultimate-crypto-comparison#7]
Provide all available libraries via the script of the Master Fachstudie.

**Comment by schneisn** [comment]
The issue with the git scrabber is that it apparently includes some forks from a library. Instead of using the git scrabber to add a whole new libary, we could use the git scrabber to get information that would have to be put in by hand otherwise. This information includes for example the used hash functions, macs, pki, etc.  
This would reduce the amount of data that needs to be collected manually.

**Comment by schneisn** [comment]
The git-scrabber will be used to retrieve information of git-repositories under the given urls in the markdown files. This automatic update will be implemented in #11.
